"""crawler

Revision ID: 60f966680eb2
Revises: 63ede865f432
Create Date: 2026-03-22 15:02:58.790323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '60f966680eb2'
down_revision: Union[str, Sequence[str], None] = '63ede865f432'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SCHEMA IF NOT EXISTS crawler')
    op.create_table('crawlsession',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_urls', sa.Integer(), nullable=False),
    sa.Column('crawled_urls', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='crawler'
    )
    op.create_index(op.f('ix_crawler_crawlsession_domain'), 'crawlsession', ['domain'], unique=False, schema='crawler')
    op.create_table('crawledurl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('crawled_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['crawler.crawlsession.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='crawler'
    )
    op.create_index(op.f('ix_crawler_crawledurl_session_id'), 'crawledurl', ['session_id'], unique=False, schema='crawler')
    op.create_index(op.f('ix_crawler_crawledurl_status_code'), 'crawledurl', ['status_code'], unique=False, schema='crawler')
    op.create_index(op.f('ix_crawler_crawledurl_url'), 'crawledurl', ['url'], unique=False, schema='crawler')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crawler_crawledurl_url'), table_name='crawledurl', schema='crawler')
    op.drop_index(op.f('ix_crawler_crawledurl_status_code'), table_name='crawledurl', schema='crawler')
    op.drop_index(op.f('ix_crawler_crawledurl_session_id'), table_name='crawledurl', schema='crawler')
    op.drop_table('crawledurl', schema='crawler')
    op.drop_index(op.f('ix_crawler_crawlsession_domain'), table_name='crawlsession', schema='crawler')
    op.drop_table('crawlsession', schema='crawler')
    op.execute('DROP SCHEMA IF EXISTS crawler')
    # ### end Alembic commands ###
